### ISSUE TITLE
Could not find property 'pinConfig' on root project

### ISSUE THREAD

**Issue by jonnyzzz** [jk1/TeamCity-dependencies-gradle-plugin#13]
Caused by: groovy.lang.MissingPropertyException: Could not find property 'pinConfig' on root project ***.
    at org.gradle.api.internal.AbstractDynamicObject.propertyMissingException(AbstractDynamicObject.java:43)
    at org.gradle.api.internal.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:35)
    at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:97)
    at org.gradle.api.internal.project.DefaultProject_Decorated.getProperty(Unknown Source)
    at com.github.jk1.tcdeps.util.ResourceLocator.setContext(ResourceLocator.groovy:24)
    at com.github.jk1.tcdeps.util.ResourceLocator$setContext.callStatic(Unknown Source)
    at com.github.jk1.tcdeps.TeamCityDependenciesPlugin$_apply_closure2.doCall(TeamCityDependenciesPlugin.groovy:42)
    at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
    at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
    at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
    at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
    at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy10.afterEvaluate(Unknown Source)
    at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
    ... 54 more

BUILD FAILED

09:46:40: External task execution finished 'clean --info --stacktrace'.

**Comment by jk1** [comment]
Fixed in 0.8.3
