### ISSUE TITLE
Plugin fails on Gradle 3.1

### ISSUE THREAD

**Issue by RaySinnema** [jk1/TeamCity-dependencies-gradle-plugin#18]
`groovy.lang.MissingMethodException: No signature of method: org.gradle.internal.component.external.model.DefaultMutableIvyModuleResolveMetadata.getConfiguration() is applicable for argument types: (java.lang.String) values: [default]
        at com.github.jk1.tcdeps.processing.DependenciesRegexProcessor.readArtifactsSet(DependenciesRegexProcessor.groovy:85)
        at com.github.jk1.tcdeps.processing.DependenciesRegexProcessor$_processDependencies_closure2.doCall(DependenciesRegexProcessor.groovy:39)
        at com.github.jk1.tcdeps.processing.DependenciesRegexProcessor.processDependencies(DependenciesRegexProcessor.groovy:31)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:382)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:80)
        at com.github.jk1.tcdeps.processing.DependenciesRegexProcessor$_process_closure7.doCall(DependenciesRegexProcessor.groovy:135)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:117)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:122)
        at org.gradle.api.DomainObjectCollection$all$0.call(Unknown Source)
        at com.github.jk1.tcdeps.processing.DependenciesRegexProcessor.process(DependenciesRegexProcessor.groovy:133)
        at com.github.jk1.tcdeps.processing.DependenciesRegexProcessor$process.call(Unknown Source)
        at com.github.jk1.tcdeps.TeamCityDependenciesPlugin$_apply_closure2.doCall(TeamCityDependenciesPlugin.groovy:44)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy14.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
        ... 52 more
`

**Comment by jonnyzzz** [comment]
👍

**Comment by jk1** [comment]
@RemonSinnema, thanks again for reporting it.
Please try updating to version 0.11, it should solve the issue.

**Comment by RaySinnema** [comment]
Thanks, this works.
