### ISSUE TITLE
Can't configure plugin from build.gradle.kts

### ISSUE THREAD

**Issue by jk1** [jk1/TeamCity-dependencies-gradle-plugin#19]
Even a simple configuration like
````
repositories {
    teamcityServer {
        url = 'https://url.domain.com'
    }
}
````

results in 

````
Caused by: java.lang.AssertionError: No resolved call for 'teamcityServer{
          setUrl("https://url.domain.com")
      }' at (19,5) in /home/jk1/Projects/consumer/build.gradle.kts
        at org.jetbrains.kotlin.resolve.calls.callUtil.CallUtilKt.getResolvedCallWithAssert(callUtil.kt:187)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitCallExpression(ExpressionCodegen.java:2625)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitCallExpression(ExpressionCodegen.java:120)
        at org.jetbrains.kotlin.psi.KtCallExpression.accept(KtCallExpression.java:35)
        at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitKtElement(CodegenStatementVisitor.java:31)
        at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitKtElement(CodegenStatementVisitor.java:22)
        at org.jetbrains.kotlin.psi.KtVisitor.visitExpression(KtVisitor.java:178)
        at org.jetbrains.kotlin.psi.KtVisitor.visitReferenceExpression(KtVisitor.java:194)
        at org.jetbrains.kotlin.psi.KtVisitor.visitCallExpression(KtVisitor.java:270)
        at org.jetbrains.kotlin.psi.KtCallExpression.accept(KtCallExpression.java:35)
        at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:293)
        ... 104 more
````

**Comment by jk1** [comment]
Implemented in 0.14
