### ISSUE TITLE
Gradle 3.4 crash

### ISSUE THREAD

**Issue by jonnyzzz** [jk1/TeamCity-dependencies-gradle-plugin#22]
Caused by: java.lang.IllegalStateException: Resolving configuration 'apiElementsCopy' directly is not allowed
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.assertResolvingAllowed(DefaultConfiguration.java:819)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:419)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1800(DefaultConfiguration.java:106)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies.getResolutionResult(DefaultConfiguration.java:957)
        at com.github.jk1.tcdeps.processing.ArtifactRegexResolver.getIvyDescriptorsForConfiguration(ArtifactRegexResolver.groovy:109)
        at com.github.jk1.tcdeps.processing.ArtifactRegexResolver.resolveArtifacts(ArtifactRegexResolver.groovy:30)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:464)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:176)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:80)
        at com.github.jk1.tcdeps.processing.ArtifactRegexResolver$_process_closure1.doCall(ArtifactRegexResolver.groovy:23)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:135)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:153)
        at org.gradle.api.DomainObjectCollection$all$0.call(Unknown Source)
        at com.github.jk1.tcdeps.processing.ArtifactRegexResolver.process(ArtifactRegexResolver.groovy:21)
        at com.github.jk1.tcdeps.processing.ArtifactRegexResolver$process.call(Unknown Source)
        at com.github.jk1.tcdeps.TeamCityDependenciesPlugin$_apply_closure2.doCall(TeamCityDependenciesPlugin.groovy:43)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy15.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
        ... 56 more

**Comment by RaySinnema** [comment]
I'm running into this issue as well. It's caused by some default Gradle configurations that are not resolvable, see https://docs.gradle.org/3.4/release-notes.html#configurations-can-be-unresolvable.

**Comment by jk1** [comment]
Fixed in 0.12
