### ISSUE TITLE
Gradle 4.3 support

### ISSUE THREAD

**Issue by jonnyzzz** [jk1/TeamCity-dependencies-gradle-plugin#30]
[TCdeps] An error occurred during artifact notation pattern resolution
[02:03:50][Step 1/1] java.lang.NoClassDefFoundError: org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/DownloadedIvyModuleDescriptorParser
[02:03:50][Step 1/1] 	at com.github.jk1.tcdeps.processing.ArtifactRegexResolver.readArtifactsSet(ArtifactRegexResolver.groovy:110)
[02:03:50][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:03:50][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:03:50][Step 1/1] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:03:50][Step 1/1] 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[02:03:50][Step 1/1] 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
[02:03:50][Step 1/1] 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
[02:03:50][Step 1/1] 	at com.github.jk1.tcdeps.processing.ArtifactRegexResolver$_resolveArtifacts_closure6.doCall(ArtifactRegexResolver.groovy:66)
[02:03:50][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:03:50][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:03:50][Step 1/1] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:03:50][Step 1/1] 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[02:03:50][Step 1/1] 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
[02:03:50][Step 1/1] 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[02:03:50][Step 1/1] 	at groovy.lang.Closure.call(Closure.java:414)
[02:03:50][Step 1/1] 	at groovy.lang.Closure.call(Closure.java:430)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2025)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2078)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.dgm$165.invoke(Unknown Source)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
[02:03:50][Step 1/1] 	at com.github.jk1.tcdeps.processing.ArtifactRegexResolver.resolveArtifacts(ArtifactRegexResolver.groovy:58)
[02:03:50][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:03:50][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:03:50][Step 1/1] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:03:50][Step 1/1] 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[02:03:50][Step 1/1] 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
[02:03:50][Step 1/1] 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
[02:03:50][Step 1/1] 	at com.github.jk1.tcdeps.processing.ArtifactRegexResolver$_process_closure2.doCall(ArtifactRegexResolver.groovy:30)
[02:03:50][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:03:50][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:03:50][Step 1/1] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:03:50][Step 1/1] 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[02:03:50][Step 1/1] 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
[02:03:50][Step 1/1] 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[02:03:50][Step 1/1] 	at groovy.lang.Closure.call(Closure.java:414)
[02:03:50][Step 1/1] 	at groovy.lang.Closure.call(Closure.java:430)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2025)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2078)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.dgm$165.invoke(Unknown Source)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
[02:03:50][Step 1/1] 	at com.github.jk1.tcdeps.processing.ArtifactRegexResolver.process(ArtifactRegexResolver.groovy:29)
[02:03:50][Step 1/1] 	at com.github.jk1.tcdeps.processing.ArtifactRegexResolver$process.call(Unknown Source)
[02:03:50][Step 1/1] 	at com.github.jk1.tcdeps.TeamCityDependenciesPlugin$_apply_closure2.doCall(TeamCityDependenciesPlugin.groovy:36)
[02:03:50][Step 1/1] 	at sun.reflect.GeneratedMethodAccessor189.invoke(Unknown Source)
[02:03:50][Step 1/1] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:03:50][Step 1/1] 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[02:03:50][Step 1/1] 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[02:03:50][Step 1/1] 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
[02:03:50][Step 1/1] 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
[02:03:50][Step 1/1] 	at groovy.lang.Closure.call(Closure.java:414)
[02:03:50][Step 1/1] 	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
[02:03:50][Step 1/1] 	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
[02:03:50][Step 1/1] 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
[02:03:50][Step 1/1] 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
[02:03:50][Step 1/1] 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
[02:03:50][Step 1/1] 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
[02:03:50][Step 1/1] 	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
[02:03:50][Step 1/1] 	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
[02:03:50][Step 1/1] 	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
[02:03:50][Step 1/1] 	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
[02:03:50][Step 1/1] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
[02:03:50][Step 1/1] 	at com.sun.proxy.$Proxy27.afterEvaluate(Unknown Source)
[02:03:50][Step 1/1] 	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:76)
[02:03:50][Step 1/1] 	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
[02:03:50][Step 1/1] 	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:34)
[02:03:50][Step 1/1] 	at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:110)
[02:03:50][Step 1/1] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
[02:03:50][Step 1/1] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
[02:03:50][Step 1/1] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
[02:03:50][Step 1/1] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
[02:03:50][Step 1/1] 	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
[02:03:50][Step 1/1] 	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:656)
[02:03:50][Step 1/1] 	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:135)
[02:03:50][Step 1/1] 	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
[02:03:50][Step 1/1] 	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
[02:03:50][Step 1/1] 	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
[02:03:50][Step 1/1] 	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:249)
[02:03:50][Step 1/1] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
[02:03:50][Step 1/1] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
[02:03:50][Step 1/1] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
[02:03:50][Step 1/1] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
[02:03:50][Step 1/1] 	at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:167)
[02:03:50][Step 1/1] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:126)
[02:03:50][Step 1/1] 	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:109)
[02:03:50][Step 1/1] 	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:78)
[02:03:50][Step 1/1] 	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:75)
[02:03:50][Step 1/1] 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
[02:03:50][Step 1/1] 	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
[02:03:50][Step 1/1] 	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:75)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
[02:03:50][Step 1/1] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
[02:03:50][Step 1/1] 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
[02:03:50][Step 1/1] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
[02:03:50][Step 1/1] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
[02:03:50][Step 1/1] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
[02:03:50][Step 1/1] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
[02:03:50][Step 1/1] 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
[02:03:50][Step 1/1] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
[02:03:50][Step 1/1] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
[02:03:50][Step 1/1] 	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
[02:03:50][Step 1/1] 	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:57)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:45)
[02:03:50][Step 1/1] 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
[02:03:50][Step 1/1] 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
[02:03:50][Step 1/1] 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
[02:03:50][Step 1/1] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:280)
[02:03:50][Step 1/1] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:253)
[02:03:50][Step 1/1] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
[02:03:50][Step 1/1] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
[02:03:50][Step 1/1] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
[02:03:50][Step 1/1] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
[02:03:50][Step 1/1] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:246)
[02:03:50][Step 1/1] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:182)
[02:03:50][Step 1/1] 	at org.gradle.launcher.Main.doAction(Main.java:33)
[02:03:50][Step 1/1] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
[02:03:50][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:03:50][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:03:50][Step 1/1] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:03:50][Step 1/1] 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:03:50][Step 1/1] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
[02:03:50][Step 1/1] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
[02:03:50][Step 1/1] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
[02:03:50][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:03:50][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:03:50][Step 1/1] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:03:50][Step 1/1] 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:03:50][Step 1/1] 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
[02:03:50][Step 1/1] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
[02:03:50][Step 1/1] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by jk1** [comment]
0.16 should have it fixed thanks to @semoro
